### ISSUE TITLE
Edit slashing article to replace bad wording

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/docs#115]
**Estimated time:** 30m

---------------

**Why:**
The wording can be a bit offending for active masternode owner who see their node slashed because of our codebase problems

**What:**
Replace "lazy masternodes" by a better wording in https://medium.com/tomochain/tomochain-slashing-mechanism-for-network-stability-and-performance-cd7e7a9320f7

**Comment by phamvancam2104** [comment]
The output of this issue is to have comments on the medium article and I'll resolve it later.

**Comment by etienne-napoleone** [comment]
"under performing"? Might be more neutral

**Comment by nyeates** [comment]
> "under performing"? Might be more neutral

Under performing is best. I had chosen weak over this, because it was easier to say :-)

This is a generalized long-term document. I do not think you need to take into account the MNs that get knocked off from stuck blocks....this will hopefully fade over time.... I sure hope so, for my health hahaha!

...But it should take into account when nodes cannot keep up with blocks because they are under performant.

**Comment by phamvancam2104** [comment]
Accepted `underperforming`

**Comment by phamvancam2104** [comment]
Lazy in the article has been replaced with `underperforming`.
