### ISSUE TITLE
Decide organization of tomo docs

### ISSUE THREAD

**Issue by nyeates** [tomochain/docs#118]
(**Why:**) We need a path forward on how to organize the docs.tomochain.com website, as well as the overall feel/strategy of docs generally.

**What:**
* Decide how the sites hierarchy is structured generally.
* Centralize everything on docs.tomo or allow other sources which can graduate to docs.tomo?
  * ex: wiki's, blogs, medium articles

**Background:** When @etienne-napoleone handed off to @phamvancam2104 the docs website was in the middle of a organizational-change to put audience-specific tutorials/walkthroughs on the "Get started" page, and to keep more technical reference material inside of deeper hierarchy. In the leadership change, this may have been lost in the shuffle.

**Comment by nyeates** [comment]
Bringing over discussion that [started here](https://github.com/tomochain/docs/issues/109)...

@phamvancam2104 commented:
@etienne-napoleone @nyeates I think the getting started page should not be as long as this awesome masternode guide. As an ordinary user, I'd to have a first overview about the masternode and the requirements for it, which should then point to this detailed, step-by-step guide. For me, putting the content of this https://docs.tomochain.com/masternode/requirements/ in Getting started page, and putting this long, detailed guide under Masternode tab would be more natural.

@etienne-napoleone commented:
It's really up to you, but to me the difficulty here is to not mix tutorial, articles, howtos, technical documentation, etc. How I see it is that the masternode section is really the technical documentation like you would do one for an api or so. For ex. the readme of the tmn redirect to https://docs.tomochain.com/masternode/tmn/ . Where the get started part could be an opinionated how-to with references to the more in depth/technical documentations in the other sections. This is for example how Docker documentation is structured. This is just how I saw the organization, if you feel like doing it in another way @phamvancam2104 , just keep in mind that tmn in not the only way of running a mn, and you would need to so a similar tutorial on running with docker + another page for the full documentation on both those solutions (or integrate the full doc in the tutorial, but seems a bit heavy)

**Comment by nyeates** [comment]
# Docs Research

## How Docker does docs
* https://docs.docker.com

Hierarchical and Centralized. Split into Guides vs Product Manuals. They seem to *try* to separate tutorials vs technical info, but often it intermixes. Seems very groomed. Uninviting for community-created-content. Most users are technical by default - no "wallet users".

## How Ethereum does docs
* http://www.ethdocs.org/
* https://solidity.readthedocs.io/
* https://github.com/ethereum/wiki/wiki
* https://www.ethereum.org/cli - Getting Started

More organic. Decentralized. Still they have hierarchy within each website, but they have many separate websites for docs. Inviting to community interaction.

## How Tron does docs (our most-similar competitor)
* https://developers.tron.network/
* https://tron-wiki.readthedocs.io/en/latest/
* https://developers.tron.network/docs
* https://github.com/tronprotocol/Documentation

Massive Quantity. Organic-Hierarchy mix. Lots of developer-oriented how-tos and docs. Various separate docs sites. They each contain LOTS of in-depth material. Better this than lack of material. Its rather impressive how they built this in 1 year.

**Comment by nyeates** [comment]
After doing a deep dive on others docs sites, I have some thoughts. Guides are the vast majority of docs on other sites. All three projects successfully weave guided-docs into the same hierarchy (folders/categories) as technical-docs. However, they are not often mixed _within the same document_.

**Hierarchy ideas:**
* Rename "Get Started" as "Common Tasks"
  * This becomes @etienne-napoleone 's user-oriented beginner-common-tasks section (masternode guide too long for it - simple version instead)
* Put a "Get started" or "Introduction" doc into each sub-section (docker does this)
* Give in-depth guide for most-common way to do something (tmn, tomowallet, metamask)
  * Give smaller partial guides or technical content for alternate ways (docker, trustwallet)
  * I like @phamvancam2104 suggestion to put my guide under masternode category, yet maybe bring some overview of it into "Common Tasks"
* Re-think our top-level menu structure and way it is shown (VERY hard to know where you are in the hierarchy)

**General thoughts:**
Organic-Hierarchy mix. We are already kind of doing this with a mix of docs.tomochain.com, wiki, medium articles, etc. This encourages community content. Docs team must always be cataloguing and linking to stuff in docs.tomo. Try to "suck-in" as much content as we can into docs.tomo. Wiki already has 7 community-written articles - I will try to keep "vetting" those.

**Comment by nyeates** [comment]
By the way... Tron and Eth's focus: dApps and developers. 80% is towards this.

**Comment by damvananh91** [comment]
Hi @nyeates thank you very much for your information. 

`Organic-Hierarchy mix. We are already kind of doing this with a mix of docs.tomochain.com, wiki, medium articles`: In fact, this is also my question for the purpose of the tech writing team. 
- Are we going to write analysis-oriented documentation or developer guide-oriented documentation? Well, I thought it should be the second one. However, the majority of what is written is not for developers, or none of them is for developers indeed.
- Is following Docker's documentation style is good? Frankly, Docker and its documentation are built for developers, not end-users. On the other hand, while some of TomoChain' products (TomoWallet, TomoMaster, TomoScan) with highly user-friendly interfaces are built for end-users, we also want to encourage developers to develop DApps on TomoChain, thus developer-oriented documentation is indispensable. 
- I think organizing our documentation page as in Decred (https://docs.decred.org/) is a good option.

1. Getting Started should be guiding the readers to read the documentation page, instead of diving into details of running masternodes. It should describe what are TomoChain products and how these products are linked together in a figure. Furthermore, it should explicitly guide voters/masternode owners/developers to go to the specific docs site/tab for that purpose.
2. Each product should have a tab page (as it currently is) which describes how to use that specific product and for what purpose.
3. Should have an advance tab for developers documentation and masternode owners.

**Comment by phamvancam2104** [comment]
Hi @nyeates thank you very much for your information.

- Organic-Hierarchy mix. We are already kind of doing this with a mix of docs.tomochain.com, wiki, medium articles: In fact, this is also my question for the purpose of the tech writing team.

- Are we going to write analysis-oriented documentation or developer guide-oriented documentation? Well, I thought it should be the second one. However, the majority of what is written is not for developers, or none of them is for developers indeed.

- Is following Docker's documentation style is good? Frankly, Docker and its documentation are built for developers, not end-users. On the other hand, while some of TomoChain' products (TomoWallet, TomoMaster, TomoScan) with highly user-friendly interfaces are built for end-users, we also want to encourage developers to develop DApps on TomoChain, thus developer-oriented documentation is indispensable.

- I think organizing our documentation page as in Decred (https://docs.decred.org/) is a good option.

1. Getting Started should be guiding the readers to read the documentation page, instead of diving into details of running masternodes. It should describe what are TomoChain products and how these products are linked together in a figure. Furthermore, it should explicitly guide voters/masternode owners/developers to go to the specific docs site/tab for that purpose.

2. Each product should have a tab page (as it currently is) which describes how to use that specific product and for what purpose.

3. Should have an advance tab for developers documentation and masternode owners.

**Comment by damvananh91** [comment]
Please refer this https://github.com/tomochain/docs/tree/tw/119 for organization of our doc site.

**Comment by phamvancam2104** [comment]
Please refer this https://github.com/tomochain/docs/tree/tw/119 for organization of our doc site.
