### ISSUE TITLE
Article on comparing EOS, Lisk and TomoChain reward engine

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/docs#71]
**Estimated time:** 5h

---------------

**Why:**
As a following to the discarded article https://github.com/tomochain/docs/issues/53, it might be better to offer a flat comparison between our voting rewards and vote manipulation possibilities rather than focusing on the problems of one of them.

**What:**
A technical comparison between EOS, Lisk and TomoChain focus on the reward system. Their advantages, differences but also how it can be abused and what is put in place to avoid that.

**Comment by anhntv2012** [comment]
Hi @patrickburm , nice to meet you :)

The introduction of article is good. I love the way you presented the development of consensus mechanisms.

There are some points I would like you to consider:

1. There is no reward comparison in your article. 

2. Rather than devoting a whole paragraph to each project, it'll be clearer to talk about one point of comparison/contrast at a time (discuss a certain point of comparison/contrast related to all projects). 
For example: How to become candidate: For EOS, for Lisk, for TomoChain etc.
You should plan a list of criteria and figure out which ones you want to discuss more deeply. 

3. An added comparison table will be very helpful (no of masternodes/delegates/block producers; how to become a candidate (deposit/fee); how often a voting round is, how to vote (fee/deposit), how to unvote, lock time; how reward is shared to voters, how reward is planned to be reduced year after year etc)

4. It'd better to have a conclusion at the end of the article.

5. You consider PoSV as a form of DPoS consensus mechanisms, which I am not sure is the way we want to promote our consensus. @phamvancam2104  @etienne-napoleone , pls tell me how you think

**Comment by etienne-napoleone** [comment]
Thanks for the feedback @anhntv2012 , I agree with the points you raised.
@patrickburm Can you update the draft regarding to the comments?

**Comment by patrickburm** [comment]
Thanks for your feedback and nice to meet you too! :) @anhntv2012 
I will update the article regarding those aspects and share the draft on medium once it's done.

**Comment by etienne-napoleone** [comment]
@patrickburm Cool, can you post the link to the draft here also?

**Comment by patrickburm** [comment]
Yes, it's more easier for everyone if I just post the medium drafts here instead of google docs link right?

**Comment by etienne-napoleone** [comment]
I do think so :)

**Comment by patrickburm** [comment]
This is how it looks now:
https://medium.com/p/9b3b26560392/edit

**Comment by etienne-napoleone** [comment]
@anhntv2012 and @phamvancam2104 could you take a look?

**Comment by anhntv2012** [comment]
Hi @patrickburm 

The updated article is better than the previous one.
Still, I'd like you to consider the following suggestions:

1. You already discussed one main point of comparison at a time for all 3 projects. However, it still needs to be clearer. If one thing is mentioned about 1 project, it should be also talked about in the other 2.
I put below all main points for ease of explanation:
*** Becoming a block producer**
- No of block producers/delegates/masternodes
- Any fee or deposit requirement to become a candidate
- What happens if a candidate/masternode wants to resign (lock time for Tomochain; waste of fee for Lisk?; EOS?)
*** Voting system**
- No of voting cast (EOS 21; TomoChain: unlimited; Lisk: 101)
- Voting weight
- Any fee or deposit requirement to vote
- What happens if a voter wants to unstake/unvote

2. Reward Engine
You should focus on the block reward rather than the circulating supply
+ Total reward: fixed, inflationary
+ Block producers/Masternodes/Delegates
+ Standby producers/candidates
+ Voters
+...

3. Others:
* How we write our brand: Tomo**C**hain (not Tomochain - this has recently been decided)
* "Full nodes who want to become candidates for the Tomochain masternode election have to deposit 50k TOMO to the voting smart contract in the Tomomaster DApp. There is no extra fee for the application and the deposited stake can be withdrawn 30 days after a _masternode_ **(should be "candidate")** resigns. Tomo stakeholders then vote for candidates via the DApp, to a total of 150 masternodes"
* "Stakeholders can decide at any time to unvote _masternodes_ **(Should be "candidates")** and vote for other ones." 
 *"The third part of 10% will go to the masternode Foundation _INITIALLY_ **(Should be added)** run by the Tomochain company to further develop the network"         

@etienne-napoleone  @phamvancam2104  Any other comments, sirs?

Best,

**Comment by patrickburm** [comment]
Thanks again for your feedback! @anhntv2012

**Comment by patrickburm** [comment]
Please check again @anhntv2012  @phamvancam2104  @etienne-napoleone 
best regards!

**Comment by anhntv2012** [comment]
Hi, for me it's good for publishing now.
Just a minor addition:
"If a TomoChain masternode/**masternode candidate** would resign, the 50k TOMO he deposited would be locked in the voting smart contract from that time for 30 days."

@phamvancam2104  @etienne-napoleone How do you think?

**Comment by etienne-napoleone** [comment]
@phamvancam2104 because his article is submited to the TomoChain channel, all TomoChain editors can view each others comments.

![image](https://user-images.githubusercontent.com/26155267/47892462-62d85d00-de8a-11e8-976c-e63a6eb696e1.png)

**Comment by phamvancam2104** [comment]
@etienne-napoleone Great! I did not notice about that :)

**Comment by phamvancam2104** [comment]
Hi @patrickburm, 
Thank you very much for your great article and I have acquired significant knowledge :). Btw, besides some minors, I think the article is ready to publish.

**Comment by patrickburm** [comment]
Thank you very much @phamvancam2104 , @anhntv2012 @etienne-napoleone  for this valuable feedback! I implemented your suggestions so I think it should be ready to publish now. I put the comparison table above the Conclusion now. By the way, thank you @phamvancam2104 for the template ;)

**Comment by etienne-napoleone** [comment]
I'm closing this issue, @alex9121 feel free to incorporate this article in your publications
