### ISSUE TITLE
Documentation on contributing to the documentation website

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/docs#93]
**Estimated time:** 6h

---------------

**Why:**
Contributing to the documentation website seems not easy for everybody. It uses a lot of my time helping each others to use the different tools (markdown, git, etc)

**What:**
A markdown file called CONTRIBUTING.md at the root of the project who explains how to contribute.
It should talk about:
- conventions:
    - branching
    - commits
    - markdown
- help for newbies:
    - git
        - cli
        - github.com
    - editors

The estimated time is quite high as the writer is expected to learn the parts that he doesn't know so much himself to be able to explain them clearly.

Ressources:
- https://github.com/tomochain/docs#contribution-guideline
- https://github.com/orgs/tomochain/teams/technical-writers/discussions/1

**Comment by etienne-napoleone** [comment]
Assigned to: @DuqueKarl 
Reviewed by: @etienne-napoleone

**Comment by etienne-napoleone** [comment]
Assigned to: @patrickburm 
Reviewed by: @etienne-napoleone 

Changed to Patrick so he can get more familiar with `git` and our doc website.

**Comment by etienne-napoleone** [comment]
Any news on this @patrickburm ?
This is quite low priority so if you haven't really started on this, I will assign you other tasks.

**Comment by patrickburm** [comment]
Sorry for my late response @etienne-napoleone , was already in the holiday mood ^^
I already startet on this and Karl also provided me useful information too because this task was related to him once. I would say it's 50% done. But unless I am on holiday till Sunday and will be able to continue working at the end of the week, I think it might be the best if you give me tasks with higher priority and I will keep on doing this task parallel if it's priority isn't that high.

**Comment by phamvancam2104** [comment]
Is this task ready for review @patrickburm?

**Comment by etienne-napoleone** [comment]
Any update @patrickburm ?

**Comment by etienne-napoleone** [comment]
Let's close that, it's not necessary
